version: "3"

services:
    restapi:
        container_name: node-rest
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mydatabase
        image: mongo
        ports:
            - "21018:27017"
        logging: 
            driver: none